namespace CollectPhoto.Properties
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator","14.0.0.0")]
	public sealed partial class Settings:global::System.Configuration.ApplicationSettingsBase
	{
		private static Settings defaultInstance=((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
		public static Settings Default
		{
			get
			{
				return defaultInstance;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public string SearchSourceDirectoriesDeepLimitation
		{
			get
			{
				return((string)(this["SearchSourceDirectoriesDeepLimitation"]));
			}
			set
			{
				this["SearchSourceDirectoriesDeepLimitation"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool FilterWhileSearching
		{
			get
			{
				return((bool)(this["FilterWhileSearching"]));
			}
			set
			{
				this["FilterWhileSearching"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool AutoDetermine
		{
			get
			{
				return((bool)(this["AutoDetermine"]));
			}
			set
			{
				this["AutoDetermine"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool AutoStart
		{
			get
			{
				return((bool)(this["AutoStart"]));
			}
			set
			{
				this["AutoStart"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool MultipleJobs
		{
			get
			{
				return((bool)(this["MultipleJobs"]));
			}
			set
			{
				this["MultipleJobs"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool CreateSubDestinationRootDirectory
		{
			get
			{
				return((bool)(this["CreateSubDestinationRootDirectory"]));
			}
			set
			{
				this["CreateSubDestinationRootDirectory"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool CopyLowGradeImage
		{
			get
			{
				return((bool)(this["CopyLowGradeImage"]));
			}
			set
			{
				this["CopyLowGradeImage"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool AutoRename
		{
			get
			{
				return((bool)(this["AutoRename"]));
			}
			set
			{
				this["AutoRename"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool DeleteAlreadyExists
		{
			get
			{
				return((bool)(this["DeleteAlreadyExists"]));
			}
			set
			{
				this["DeleteAlreadyExists"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool DeleteAfterCopy
		{
			get
			{
				return((bool)(this["DeleteAfterCopy"]));
			}
			set
			{
				this["DeleteAfterCopy"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string Command
		{
			get
			{
				return((string)(this["Command"]));
			}
			set
			{
				this["Command"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string CommandOptions
		{
			get
			{
				return((string)(this["CommandOptions"]));
			}
			set
			{
				this["CommandOptions"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string SourceDirectories
		{
			get
			{
				return((string)(this["SourceDirectories"]));
			}
			set
			{
				this["SourceDirectories"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string DestinationRootDirectory
		{
			get
			{
				return((string)(this["DestinationRootDirectory"]));
			}
			set
			{
				this["DestinationRootDirectory"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool DeleteReadOnly
		{
			get
			{
				return((bool)(this["DeleteReadOnly"]));
			}
			set
			{
				this["DeleteReadOnly"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string IncludeFileExtensions
		{
			get
			{
				return((string)(this["IncludeFileExtensions"]));
			}
			set
			{
				this["IncludeFileExtensions"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string ExcludeFileExtensions
		{
			get
			{
				return((string)(this["ExcludeFileExtensions"]));
			}
			set
			{
				this["ExcludeFileExtensions"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string ImageFileExtensions
		{
			get
			{
				return((string)(this["ImageFileExtensions"]));
			}
			set
			{
				this["ImageFileExtensions"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string SearchDirectoriesBypassPatterns
		{
			get
			{
				return((string)(this["SearchDirectoriesBypassPatterns"]));
			}
			set
			{
				this["SearchDirectoriesBypassPatterns"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string DestinationSubDirectories
		{
			get
			{
				return((string)(this["DestinationSubDirectories"]));
			}
			set
			{
				this["DestinationSubDirectories"]=value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string FileNameComponent
		{
			get
			{
				return((string)(this["FileNameComponent"]));
			}
			set
			{
				this["FileNameComponent"]=value;
			}
		}
	}
}
